set nocompatible
filetype on
filetype indent on
syntax on
set number
set cursorline
set tabstop=4
set autoindent
set shiftwidth=4
set incsearch
set smartcase
set wildmenu
set wildmode=list:longest
set laststatus=2
set ruler
set noerrorbells
set wildmenu
set wildmode=longest:list,full
set noswapfile
